feat: add image paste functionality to text area
stakwork/sphinx-tribes-frontend pull request #806
Opened 2024-12-20 11:19 UTC by jordan-ae

## Describe your changes

## Issue ticket: #789 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

2024-12-20 13:57 UTC, jordan-ae commented
@humansinstitute everything is working to spec but the endpoint for uploads keeps returning a 404. Not sure what's up implementation is on point. Can we double check the endpoint please? I've been debugging for hours now and atp I'm not sure what's going on

[Screencast from 2024-12-20 14-43-22.webm](https://github.com/user-attachments/assets/a826a908-dbd0-478c-8d10-274af1cf52c1)

2024-12-21 05:02 UTC, humansinstitute commented
@tobi-bams can you review and advise on the endpoint?

2024-12-22 12:24 UTC, tobi-bams requested changes

2024-12-22 12:24 UTC, tobi-bams commented on src/components/common/TicketEditor/TicketEditor.tsx
> +                  {isPreview ? 'Preview' : 'Edit'}
If it is in preview state, the Edit button should be what is visible and when it's in Edit phase the button should say Edit.

2024-12-22 12:30 UTC, tobi-bams commented
> @humansinstitute everything is working to spec but the endpoint for uploads keeps returning a 404. Not sure what's up implementation is on point. Can we double check the endpoint please? I've been debugging for hours now and atp I'm not sure what's going on
> 
>  Screencast.from.2024-12-20.14-43-22.webm

@jordan-ae you are correct, So sorry the mistake is from my end.

The `/public_pic` endpoint has been removed, we now use the `meme_upload` endpoint. But don't worry I will handle this myself. Currently the `meme_upload` is not working properly because we've fully migrated to v2. I need to chat Evan up.
@humansinstitute

2024-12-23 04:35 UTC, humansinstitute commented
@tobi-bams - thanks for letting me know. Can you tag me when thats done and we can merge this? 

looking forward to getting this functionality!

2024-12-30 01:22 UTC, humansinstitute commented
@tobi-bams - I'm going to merge this and payout bounty for now. 

I think we can revisit and update the endpoint when you have had a chance to talk to Evan.

2024-12-30 01:22 UTC, merged